### ISSUE TITLE
cannot create the internal loadbalancer 

### ISSUE THREAD

**Issue by atlas4it** [Hamza-Mandviwala/OCP4.10.3-install-GCP-UPI#1]
# gcloud deployment-manager deployments create ${INFRA_ID}-infra --config=02_infra.yaml  --automatic-rollback-on-error
The fingerprint of the deployment is b'adSb6Jlwe2m5SzWsCtqHXg=='
Waiting for create [operation-1652922596380-5df530832d04b-9d939005-3f770eea]...failed.
WARNING: There was an error deploying focuscluster-hxdtk-infra:
Error in Operation [operation-1652922596380-5df530832d04b-9d939005-3f770eea]: errors:
- code: MANIFEST_EXPANSION_USER_ERROR
  location: /deployments/focuscluster-hxdtk-infra/manifests/manifest-1652922596435
  message: "Manifest expansion encountered the following errors: Resource name 'focuscluster-hxdtk-master--instance-group'\
    \ is not unique in 02_lb_int.py. Resource: {'name': 'focuscluster-hxdtk-master--instance-group',\
    \ 'type': 'compute.v1.instanceGroup', 'properties': {'namedPorts': [{'name': 'ignition',\
    \ 'port': 22623}, {'name': 'https', 'port': 6443}], 'network': '', 'zone': ''}}\
    \ Resource: config"

`--automatic-rollback-on-error` flag was supplied; deleting failed deployment...
Waiting for delete [operation-1652922601928-5df53088777b8-27d3ae19-a03b1610]...done.
NAME                                                     TYPE    STATUS  TARGET                    ERRORS                           WARNINGS
operation-1652922596380-5df530832d04b-9d939005-3f770eea  insert  DONE    focuscluster-hxdtk-infra  [MANIFEST_EXPANSION_USER_ERROR]  []
operation-1652922601928-5df53088777b8-27d3ae19-a03b1610  delete  DONE    focuscluster-hxdtk-infra  []                               []

**Comment by Hamza-Mandviwala** [comment]
@atlas4it - I suspect there could be a possibility that the env variables in step 23 (especially the network & zones related env variables) might not have been correctly set. Consequently, this would have led to the `02_infra.yaml` file to have certain fields empty (kindly check this at your end). I tried replicating your scenario by deliberately unsetting the network related & zones related env variables, then created the `02_infra.yaml` file and finally executed the `gcloud deployment-manager deployments create ${INFRA_ID}-infra --config=02_infra.yaml` command, and I ran into the same error as yours:
```
root@bastion-host:~# gcloud deployment-manager deployments create ${INFRA_ID}-infra --config 02_infra.yaml
The fingerprint of the deployment is b'nnOyf-3WUKrr4eyxuwh03A=='
Waiting for create [operation-1652933316689-5df55872dbed2-78589b0a-85c31512]...failed.                                                             
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1652933316689-5df55872dbed2-78589b0a-85c31512]: errors:
- code: MANIFEST_EXPANSION_USER_ERROR
  location: /deployments/hamzacluster-g4frb-infra/manifests/manifest-1652933316764
  message: "Manifest expansion encountered the following errors: Resource name 'hamzacluster-g4frb-master--instance-group'\
    \ is not unique in 02_lb_int.py. Resource: {'name': 'hamzacluster-g4frb-master--instance-group',\
    \ 'type': 'compute.v1.instanceGroup', 'properties': {'namedPorts': [{'name': 'ignition',\
    \ 'port': 22623}, {'name': 'https', 'port': 6443}], 'network': '', 'zone': ''}}\
    \ Resource: config"

```

Below is the *incorrect* 02_infra.yaml file that got created as a result of missing env variables (I suspect, your file might look similar):
```
imports:
- path: 02_lb_int.py
resources:
- name: cluster-lb-int
  type: 02_lb_int.py
  properties:
    cluster_network: ''
    control_subnet: ''
    infra_id: 'hamzacluster-g4frb'
    region: 'asia-northeast1'
    zones:
    - ''
    - ''
    - ''
```

From your error block also, we can see that the `network:` & `zone:` fields are empty (i.e no value assigned to it), which is why I feel you might want to inspect your env variables and the `02_infra.yaml` file to see if any network or zone fields aren't empty.

**Comment by atlas4it** [comment]
thanks for replying,
that's solved my issue.

**Comment by Hamza-Mandviwala** [comment]
Thanks for the update. Closing this issue.
